### ISSUE TITLE
Remove screen_sharing_app recipe

### ISSUE THREAD

**Issue by wendorf** [pivotal-sprout/sprout-osx-settings#24]
@aramprice @hiremaga What is the purpose to this recipe? Screen Sharing is accessible in its original location.

**Comment by hiremaga** [comment]
To make screen sharing visible to spotlight. Not sure if it's needed on El
Capitan.

**Comment by wendorf** [comment]
It is visible in Spotlight on El Capitan. Let's remove this recipe.

**Comment by aramprice** [comment]
agreed, all around.

**Comment by trinitronx** [comment]
@wendorf, @cunnie @hiremaga: 

😞 This breaks things for those of us stuck on `10.9.5` Mavericks or `10.10.5` Yosemite.  Believe me, I'd update if it wasn't such a painful process at my company but due to other software installed on our systems, we're still stuck with it for now.  I also depend on Screen Sharing app for VNC connections, and it's very nice to have it quickly accessible from Spotlight.

This is a breaking change for anyone using or depending on this cookbook, and should have at least been reflected with a major version bump [as per SemVer][1].

If this isn't causing any issues being kept around but unused on El Capitan, would it be too much trouble to re-instate it please?

[1]: semver.org

**Comment by hiremaga** [comment]
@cuzella is it option for you to "vendor" this recipe into your sprout-wrap
instead? it's a common pattern to turn sprout-wrap into a team specific
cookbook.

**Comment by wendorf** [comment]
@trinitronx ,

Thanks for your concern. I've reverted the commit for now while we discuss it, since I'd rather keep things working for you before we come to an ultimate decision.

Ultimately, considering the small amount of resources we're able to spend on Sprout, I'd like to focus on supporting only the latest version of OS X, but I do understand that that can cause difficulties if you're unable to update.

I'm going to think about the best way to handle supporting older versions of OS X. Is semver enough? Force people to lock to SHAs instead? Maybe a sprout-deprecated cookbook for all of the recipes put to pasture?

Let's use this issue to discuss our options. All thoughts are welcome.

**Comment by trinitronx** [comment]
@wendorf, @hiremaga :  Any of these solutions sound great!  I'd be fine with moving it to a deprecated cookbook, or vendoring my own, although that means I'd have to keep `sprout-osx-settings` locked to an older version, unable to benefit from any potential future fixes or updates.  SemVer bump is probably recommended "best practice" if you really want to remove this recipe.

It just seemed easiest to me to ask if the recipe could be left alone, since it requires low effort, and doesn't hurt anything to have unused code except if there's some implied expectation of future support, of which you're perfectly free to refuse if it's not something Pivotal is actively using.  Maybe add a note to the README if it's not working or not appropriate for later versions of OS X `>= 10.11.1` El Capitan?

I'd be happy to create a pull request to put a version guard into the recipe if it's broken or not applicable for `>= 10.11.1`.  Should be as easy as adding something to the top like:

```
raise "ERROR: Platform Unsupported - this recipe is unsupported on OS X >= 10.11 (El Capitan)" if Chef::VersionConstraint.new(">= 10.11").include?(node['platform_version'])
```

**Comment by hiremaga** [comment]
Some historical context about SemVer and Sprout: one reason we aren't doing
that is because folks still consume Sprout's cookbooks directly from
Github. If we started publishing them to the Chef supermarket it might be
natural to start versioning with SemVer, much like a rubygem.

**Comment by aramprice** [comment]
Going to archive the repo, closing.
